Reverse SOA instead of sorting.
msc01/soacsv2mt940 pull request #6
Opened 2020-05-08 09:20 UTC by zagy

Actually, the SOA _is_ sorted, but the wrong way around. Sorting
like before would sort by day-month-year which is obviously wrong
and causes wrong saldo.

2020-05-09 09:12 UTC, msc01 commented
Thanks for pointing this out! You are right, sorting by :buchungstag, hence day-month-year is wrong.

As you never know in what order a SOA file might come in, the sort order needs to be enforced because certain functionality for preparing a correct .mt940 file structure depends on the SOA being ordered by date. Therefore, reversing the SOA might lead to unintended consequences, too.

From my point of view, sorting the SOA by date is needed, but it's done in the wrong way with :buchungstag structured day-month-year; it needs to be sorted in the form of year-month-day.

What do you think?

2020-05-09 15:34 UTC, msc01 requested changes
I would go for something like this:

`csv_data.sort_by { |row| DateTime.parse(row[:buchungstag]) }`

2020-05-09 16:13 UTC, zagy commented
Well. We're talking about what commerzbank produces, not some generic thing. Currently(?) it is sorted reverse of what you'd need in MT940. But I _suppose_ it would be possible to sort by date. I'll try what happens in a next Friday (there will be enough transactions then). Our accounting software is pretty picky about the thing, so we'll know :)

2020-05-10 20:45 UTC, msc01 commented
Here’s my thought process regarding this in a little more detail:

The .csv statement of account file I receive by exporting from Commerzbank’s website currently is sorted starting with the youngest and ending with the oldest record; which is odd from my point of view as it’s contrary to what a statement of account in written or paper form looks like. 

Generally I tend to be cautious at the interface level with input data be it its structure or order; Commerzbank changed the format of the .csv file some time ago, for instance, and added the new field »kategorie« without notice. That’s why I prefer sorting the raw data so that I / my program knows what to expect. 

From a technical point of view the type 61 records („Umsätze“) of the MT940 file not necessarily need to be sorted in any form.

At the functional level I do extract the date of the statement of account (»datum_kontoauszug«) from the field »buchungstag« of the youngest record as no »datum_kontoauszug« is provided in the .csv file. It’s just an approximation, but I gave it some thought and think it’s a reasonable one as it at least comes close to what the date of the statement of account is in written or paper form. The other approach would have been to use the current date for »datum_kontoauszug«, but this might lead to odd situations when processing older SOA data. 

The date of a statement of account needs to be filled in the footer (type 62 record) of the MT940 file. So when processing the SOA in the „natural“ order like in written / paper form (youngest last) it comes very handy that the »buchungstag« of the last type 61 record is still there an can easily be used as the »datum_kontoauszug«.

That’s why sorting the SOA by »buchungstag« imho in the current version is needed. But it’s of course needed in the form of year-month-day and not day-month-year; I do totally agree that the latter was a mistake by me and really do appreciate your pointing this out to me!

A great enhancement of the current version of the program would be having an optional parameter defining the sort order being ascending/descending; but then another parameter would be needed for supplying the date of the statement of account, too. And that would be a bigger change...will put it on the list for the next version!

2020-05-11 12:16 UTC, msc01 commented
Bug "wrong sort order due to form of date »:buchungstag« being dd-mm-yy instead of yy-mm-dd" fixed with [commit 27447c5c4fa96acd6b3adcf93059529a5626b539](https://github.com/msc01/soacsv2mt940/commit/27447c5c4fa96acd6b3adcf93059529a5626b539).

2020-05-15 06:39 UTC, zagy commented
Sorting the SOA by date works. Accounting didn't barf. So, that's fine. I'm closing my PR.

2020-05-15 06:39 UTC, closed without merging